In [2]:
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from sklearn.linear_model import LogisticRegression

In [3]:
# Opening the file
data = pd.read_csv('train.txt', sep=",")

In [4]:
# Learning types of file
print(data.dtypes)

orderItemID         int64
orderDate          object
deliveryDate       object
itemID              int64
size               object
color              object
manufacturerID      int64
price             float64
customerID          int64
salutation         object
dateOfBirth        object
state              object
creationDate       object
returnShipment      int64
dtype: object

In [5]:
# Taking reasonable data
allDataFirst = [d for d in zip(data['orderDate'], data['deliveryDate']) if list(d)[1] != "?"  ]
allDataAll = [list(d) for d in allDataFirst if datetime.strptime(list(d)[0], '%Y-%m-%d') < datetime.strptime(list(d)[1], '%Y-%m-%d')]

In [6]:
# Calculating ship time
shipTime = [(datetime.strptime(d[1], '%Y-%m-%d')-datetime.strptime(d[0], '%Y-%m-%d')) / timedelta (days=1) for d in allDataAll]

In [7]:
# Calculating mean value
shiptimeMean = np.mean(np.array(shipTime))
print(shiptimeMean)

10.751377208123692

In [8]:
# First changin ? with orderDate + Mean
clearedDataFirst = [list(d) if list(d)[1] != "?" else [list(d)[0],(datetime.strptime(list(d)[0], '%Y-%m-%d')+ timedelta(days=11)).strftime("%Y-%m-%d")]  for d in zip(data['orderDate'], data['deliveryDate']) ]

In [9]:
# Second changing 1990 with orderDate + Mean
clearedTimeDataSecond = [d if datetime.strptime(list(d)[0], '%Y-%m-%d') < datetime.strptime(list(d)[1], '%Y-%m-%d') else [d[0],(datetime.strptime(list(d)[0], '%Y-%m-%d') + timedelta(days=11)).strftime("%Y-%m-%d")] for d in clearedDataFirst]

In [10]:
# Changing data with new values
data["orderDate"] = [row[0] for row in clearedTimeDataSecond]
data["deliveryDate"] = [row[1] for row in clearedTimeDataSecond]

In [11]:
data.head(70)

,orderItemID,orderDate,deliveryDate,itemID,size,color,manufacturerID,price,customerID,salutation,dateOfBirth,state,creationDate,returnShipment
0,1,2012-04-01,2012-04-03,186,m,denim,25,69.90,794,Mrs,1965-01-06,Baden-Wuerttemberg,2011-04-25,0
1,2,2012-04-01,2012-04-03,71,9+,ocher,21,69.95,794,Mrs,1965-01-06,Baden-Wuerttemberg,2011-04-25,1
2,3,2012-04-01,2012-04-03,71,9+,curry,21,69.95,794,Mrs,1965-01-06,Baden-Wuerttemberg,2011-04-25,1
3,4,2012-04-02,2012-04-13,22,m,green,14,39.90,808,Mrs,1959-11-09,Saxony,2012-01-04,0
4,5,2012-04-02,2012-04-13,151,39,black,53,29.90,825,Mrs,1964-07-11,Rhineland-Palatinate,2011-02-16,0
5,6,2012-04-02,2012-04-13,598,xxl,brown,87,89.90,825,Mrs,1964-07-11,Rhineland-Palatinate,2011-02-16,0
6,7,2012-04-02,2012-04-13,15,39,black,1,129.90,825,Mrs,1964-07-11,Rhineland-Palatinate,2011-02-16,0
7,8,2012-04-02,2012-04-03,32,xxl,brown,3,21.90,850,Mrs,1948-04-08,North Rhine-Westphalia,2011-02-16,1
8,9,2012-04-02,2012-04-03,32,xxl,red,3,21.90,850,Mrs,1948-04-08,North Rhine-Westphalia,2011-02-16,1
9,10,2012-04-02,2012-04-03,57,xxl,green,3,39.90,850,Mrs,1948-04-08,North Rhine-Westphalia,2011-02-16,1
10,11,2012-04-02,2012-04-03,2,xxl,mocca,2,39.90,850,Mrs,1948-04-08,North Rhine-Westphalia,2011-02-16,1
11,12,2012-04-02,2012-04-03,259,39,black,1,119.90,850,Mrs,1948-04-08,North Rhine-Westphalia,2011-02-16,1
12,13,2012-04-02,2012-04-03,603,39,black,55,169.90,850,Mrs,1948-04-08,North Rhine-Westphalia,2011-02-16,1
13,14,2012-04-02,2012-04-10,259,39,ocher,1,119.90,850,Mrs,1948-04-08,North Rhine-Westphalia,2011-02-16,1
14,15,2012-04-02,2012-04-03,165,37,mocca,47,89.90,858,Mrs,?,Berlin,2012-03-29,1
15,16,2012-04-02,2012-04-04,605,43,anthracite,1,199.90,860,Mrs,1963-08-15,North Rhine-Westphalia,2011-03-20,0
16,17,2012-04-02,2012-04-04,606,37,green,1,69.90,860,Mrs,1963-08-15,North Rhine-Westphalia,2011-03-20,1
17,18,2012-04-02,2012-04-04,55,37,green,1,89.90,860,Mrs,1963-08-15,North Rhine-Westphalia,2011-03-20,1
18,19,2012-04-02,2012-04-04,79,37,olive,1,139.90,860,Mrs,1963-08-15,North Rhine-Westphalia,2011-03-20,1
19,20,2012-04-02,2012-04-04,57,m,petrol,3,39.90,860,Mrs,1963-08-15,North Rhine-Westphalia,2011-03-20,1
20,21,2012-04-02,2012-04-04,38,m,blue,25,49.90,860,Mrs,1963-08-15,North Rhine-Westphalia,2011-03-20,1
21,22,2012-04-02,2012-04-04,231,37,green,24,99.90,860,Mrs,1963-08-15,North Rhine-Westphalia,2011-03-20,1
22,23,2012-04-02,2012-04-04,100,37,brown,43,119.90,860,Mrs,1963-08-15,North Rhine-Westphalia,2011-03-20,0
23,24,2012-04-02,2012-04-04,114,37,grey,43,129.90,860,Mrs,1963-08-15,North Rhine-Westphalia,2011-03-20,1
24,25,2012-04-02,2012-04-04,286,37,brown,1,129.90,860,Mrs,1963-08-15,North Rhine-Westphalia,2011-03-20,0
25,26,2012-04-02,2012-04-04,262,37,red,12,99.90,860,Mrs,1963-08-15,North Rhine-Westphalia,2011-03-20,1
26,27,2012-04-02,2012-04-09,607,43,black,1,149.90,860,Mrs,1963-08-15,North Rhine-Westphalia,2011-03-20,0
27,28,2012-04-02,2012-05-04,173,m,brown,20,49.90,860,Mrs,1963-08-15,North Rhine-Westphalia,2011-03-20,0
28,29,2012-04-02,2012-05-04,146,m,olive,3,24.90,860,Mrs,1963-08-15,North Rhine-Westphalia,2011-03-20,0
29,30,2012-04-02,2012-05-04,163,37,green,53,49.90,860,Mrs,1963-08-15,North Rhine-Westphalia,2011-03-20,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,41,2012-04-02,2012-04-03,182,42,ecru,17,109.90,896,Mrs,1968-12-21,Hesse,2011-03-28,1
41,42,2012-04-02,2012-04-03,138,l,curry,46,39.90,900,Mrs,1940-03-07,North Rhine-Westphalia,2011-06-07,0
42,43,2012-04-02,2012-04-03,138,l,blue,46,39.90,900,Mrs,1940-03-07,North Rhine-Westphalia,2011-06-07,0
43,44,2012-04-02,2012-04-03,108,xxl,blue,46,39.90,905,Mrs,1966-09-13,Bremen,2011-02-16,1
44,45,2012-04-02,2012-04-03,193,41,black,53,79.90,905,Mrs,1966-09-13,Bremen,2011-02-16,1
45,46,2012-04-02,2012-04-03,59,unsized,grey,32,19.90,905,Mrs,1966-09-13,Bremen,2011-02-16,0
46,47,2012-04-02,2012-04-03,29,xl,black,20,69.90,905,Mrs,1966-09-13,Bremen,2011-02-16,1
47,48,2012-04-02,2012-04-03,218,xxl,turquoise,42,89.90,905,Mrs,1966-09-13,Bremen,2011-02-16,0
48,49,2012-04-02,2012-04-03,184,xxl,red,36,99.90,905,Mrs,1966-09-13,Bremen,2011-02-16,1
49,50,2012-04-02,2012-04-03,271,s,magenta,5,59.90,913,Mrs,1966-05-09,North Rhine-Westphalia,2011-02-16,0
50,51,2012-04-02,2012-04-03,71,10+,ocher,21,69.95,915,Mrs,1968-08-23,North Rhine-Westphalia,2011-02-16,1
51,52,2012-04-02,2012-04-03,452,40,purple,1,89.90,916,Mrs,1966-01-24,Bavaria,2011-12-19,0
52,53,2012-04-02,2012-04-03,57,s,mocca,3,39.90,916,Mrs,1966-01-24,Bavaria,2011-12-19,0
53,54,2012-04-02,2012-04-03,268,s,pink,2,49.90,916,Mrs,1966-01-24,Bavaria,2011-12-19,0
54,55,2012-04-02,2012-05-17,479,40,brown,17,129.90,916,Mrs,1966-01-24,Bavaria,2011-12-19,0
55,56,2012-04-02,2012-04-03,22,m,blue,14,39.90,920,Mrs,1945-01-22,Berlin,2012-03-24,0
56,57,2012-04-02,2012-04-03,399,36,black,17,129.90,920,Mrs,1945-01-22,Berlin,2012-03-24,0
57,58,2012-04-02,2012-04-03,195,m,blue,46,19.90,924,Mrs,1943-12-28,Bavaria,2011-10-11,0
58,59,2012-04-02,2012-04-03,615,152,khaki,30,69.95,924,Mrs,1943-12-28,Bavaria,2011-10-11,0
59,60,2012-04-02,2012-04-03,337,152,navy,30,19.95,924,Mrs,1943-12-28,Bavaria,2011-10-11,0
60,61,2012-04-02,2012-04-03,616,152,khaki,30,59.95,924,Mrs,1943-12-28,Bavaria,2011-10-11,1
61,62,2012-04-02,2012-04-11,617,35,habana,15,52.95,924,Mrs,1943-12-28,Bavaria,2011-10-11,0
62,63,2012-04-02,2012-05-11,614,34,silver,48,59.95,924,Mrs,1943-12-28,Bavaria,2011-10-11,1
63,64,2012-04-02,2012-06-20,93,m,brown,20,49.90,924,Mrs,1943-12-28,Bavaria,2011-10-11,0
64,65,2012-04-02,2012-04-13,614,35,silver,48,59.95,924,Mrs,1943-12-28,Bavaria,2011-10-11,0
65,66,2012-04-02,2012-04-24,239,unsized,brown,60,0.00,925,Mrs,1958-05-08,Hesse,2011-03-16,0
66,67,2012-04-02,2012-04-13,346,xl,black,5,69.90,72,Mrs,1953-11-23,Baden-Wuerttemberg,2011-02-16,0
67,68,2012-04-02,2012-04-13,346,xl,mocca,5,69.90,72,Mrs,1953-11-23,Baden-Wuerttemberg,2011-02-16,0
68,69,2012-04-02,2012-04-13,346,xl,purple,5,69.90,72,Mrs,1953-11-23,Baden-Wuerttemberg,2011-02-16,0
69,70,2012-04-02,2012-04-03,141,xl,black,25,69.90,72,Mrs,1953-11-23,Baden-Wuerttemberg,2011-02-16,1

In [12]:
# Feature 1, if taken date > 10 1, else 0
shipmentDateF = np.array([ 0 if ((datetime.strptime(list(d)[1], '%Y-%m-%d')-datetime.strptime(list(d)[0], '%Y-%m-%d')) / timedelta (days=1)) <= 10 else 1 for d in zip(data['orderDate'], data['deliveryDate'])])

In [13]:
# Feature 2 - specialDateChrismass, if order is close to speacial date and came late it is 1
# Feature 3 - specialDateOthers, if order is close to speacial date and came late it is 1
dateRepresentationOfData = [ [(int('%02d' % datetime.strptime(list(d)[0], '%Y-%m-%d').day),int('%02d' % datetime.strptime(list(d)[0], '%Y-%m-%d').month)), (int('%02d' % datetime.strptime(list(d)[1], '%Y-%m-%d').day),int('%02d' % datetime.strptime(list(d)[1], '%Y-%m-%d').month))] for d in zip(data['orderDate'], data['deliveryDate'])]
specialDateChrismassF = np.array([1 if (d[0][0] > 14 and d[0][0] < 22 and d[0][1] == 12) and (d[1][0] >= 1 and d[1][1] >= 1) else 0 for d in dateRepresentationOfData])
specialDateOthersF = np.array([1 if (d[0][0] > 3 and d[0][0] < 11 and d[0][1] == 5) and (d[1][0] >= 15 and d[1][1] >= 5) or (d[0][0] > 8 and d[0][0] < 14 and d[0][1] == 2) and (d[1][0] >= 18 and d[1][1] >= 2) else 0 for d in dateRepresentationOfData])

In [ ]:
# Calculating age mean
allDataFirstAge = [d for d in data['dateOfBirth'] if d != "?"  ]
allDataAllAge = [d for d in allDataFirstAge if datetime.strptime(d, '%Y-%m-%d') > datetime.strptime("1930-01-01", '%Y-%m-%d') and datetime.strptime(d, '%Y-%m-%d') < datetime.strptime("2000-01-01", '%Y-%m-%d')]

ageYear = [((datetime.strptime("2014-01-01", '%Y-%m-%d')-datetime.strptime(d, '%Y-%m-%d'))/timedelta (days=1))/365 for d in allDataAllAge]
ageYearMean = np.mean(np.array(ageYear))

In [ ]:
# Clearing the birthdate data
allDataFirstAgeChanged = [d if d != "?" else (datetime.strptime("2014-01-01", '%Y-%m-%d') - timedelta(days=48)).strftime('%Y-%m-%d') for d in data['dateOfBirth']   ]
allDataAllAgeChanged = [d if datetime.strptime(d, '%Y-%m-%d') > datetime.strptime("1930-01-01", '%Y-%m-%d') and datetime.strptime(d, '%Y-%m-%d') < datetime.strptime("2000-01-01", '%Y-%m-%d') else (datetime.strptime("2014-01-01", '%Y-%m-%d') - timedelta(days=48*365.2)).strftime('%Y-%m-%d') for d in allDataFirstAgeChanged]
data["dateOfBirth"] = allDataAllAgeChanged

In [ ]:
# Feature 4, <30 - 0 , 30-55 - 1, 55> - 2
ageNummArray = [((datetime.strptime("2014-01-01", '%Y-%m-%d')-datetime.strptime(d, '%Y-%m-%d'))/timedelta (days=1))/365 for d in data['dateOfBirth']]
ageNumF = np.array([0 if d <= 30 else (1 if d <= 55 else 2) for d in ageNummArray])

In [ ]:
# Feature 5 manufacturer id mean value
groupedMeanManuReturnRate = data.groupby('manufacturerID').mean()['returnShipment']
manuReturnRateF = np.array([groupedMeanManuReturnRate[d] for d in data["manufacturerID"]])

In [ ]:
# Feature 6 costumer id mean value
groupedMeanUserReturnRate = data.groupby('customerID').mean()['returnShipment']
userReturnRateF = np.array([groupedMeanUserReturnRate[d] for d in data["customerID"]])

In [ ]:
# Feature 7 color
colorDict = {}
colorArary = ['denim', 'ocher', 'curry', 'green', 'black', 'brown', 'red', 'mocca',
 'anthracite', 'olive', 'petrol', 'blue', 'grey', 'beige', 'ecru', 'turquoise',
 'magenta', 'purple', 'pink', 'khaki', 'navy', 'habana', 'silver', 'white',
 'nature', 'stained', 'orange', 'azure', 'apricot', 'mango', 'berry', 'ash',
 'hibiscus', 'fuchsia', 'dark denim', 'mint', 'ivory', 'yellow',
 'bordeaux', 'pallid', 'ancient', 'baltic blue', 'almond', 'aquamarine',
 'aubergine','aqua', 'dark garnet', 'dark grey', 'avocado', 'creme',
 'champagner', 'cortina mocca', 'currant purple', 'cognac', 'aviator', 'gold',
 'ebony', 'cobalt blue', 'kanel','curled', 'caramel', 'antique pink',
 'darkblue', 'copper coin', 'terracotta', 'basalt', 'amethyst', 'coral', 'jade',
 'opal', 'striped', 'mahagoni', 'floral', 'dark navy', 'dark oliv', 
 'vanille', 'ingwer', 'iron', 'graphite', 'leopard', 'bronze', 'crimson',
 'lemon', 'perlmutt']

for index, x in enumerate(colorArary):
    colorDict[x] = index
colorDataF = list(data['color'])
for index, x in enumerate(colorDataF):
    if x  == "?":
        colorDataF[index] = "black"
    elif x  == "brwon":
        colorDataF[index] = "brown"
    elif x  == "blau":
        colorDataF[index] = "blue"
    elif x  == "oliv":
        colorDataF[index] = "olive"
    colorDataF[index] = colorDict[colorDataF[index]]
colorDataF = np.array(colorDataF)

In [ ]:
# Creating train matrix
trainMatrix = np.vstack((shipmentDateF, specialDateChrismassF, specialDateOthersF, ageNumF, manuReturnRateF, userReturnRateF, colorDataF)).T

In [ ]:
# Creating label array
labelArray = np.array(data['returnShipment'])

In [15]:
trainMatrix.describe()

NameError: name 'trainMatrix' is not defined

In [185]:
logisticRegr = LogisticRegression()
logisticRegr.fit(trainMatrix, labelArray)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [186]:
# Test to Feature
testData = pd.read_csv('test.txt', sep=",")

In [189]:
testshipmentDateF = np.array([ 0 if ((datetime.strptime(list(d)[1], '%Y-%m-%d')-datetime.strptime(list(d)[0], '%Y-%m-%d')) / timedelta (days=1)) <= 10 else 1 for d in zip(testData['orderDate'], testData['deliveryDate'])])

ValueError: time data '?' does not match format '%Y-%m-%d'

In [ ]:
testdateRepresentationOfData = [ [(int('%02d' % datetime.strptime(list(d)[0], '%Y-%m-%d').day),int('%02d' % datetime.strptime(list(d)[0], '%Y-%m-%d').month)), (int('%02d' % datetime.strptime(list(d)[1], '%Y-%m-%d').day),int('%02d' % datetime.strptime(list(d)[1], '%Y-%m-%d').month))] for d in zip(data['orderDate'], data['deliveryDate'])]
testspecialDateChrismassF = np.array([1 if (d[0][0] > 14 and d[0][0] < 22 and d[0][1] == 12) and (d[1][0] >= 1 and d[1][1] >= 1) else 0 for d in testdateRepresentationOfData])
testspecialDateOthersF = np.array([1 if (d[0][0] > 3 and d[0][0] < 11 and d[0][1] == 5) and (d[1][0] >= 15 and d[1][1] >= 5) or (d[0][0] > 8 and d[0][0] < 14 and d[0][1] == 2) and (d[1][0] >= 18 and d[1][1] >= 2) else 0 for d in testdateRepresentationOfData])